baseURL = "https://example.com"
languageCode = "en-us"
title = "Don Quixote"
theme = "rocinante"
paginate = 3
summaryLength = 0

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[author]
  name = "Sid Verma"

[params]
  mainSections = ["post", "photos"]
  email = "email@example.com"
  favicon = "/icon/favicon.jpg"
  about = """
Hi. I'm **Don**. Some people also know me as Alonso Quixano.

I ride around on my dear horse called _Rocinante_, being the best knight I can be. I named horse Rocinante because it's the best and the most powerful horse around.

_If you see injustice around you, and need the help of an ingenious gentleman, feel free to reach out anytime. I'm usually always available._
"""

  [[params.links]]
    [[params.links.link]]
      name = "About"
      href = "https://en.wikipedia.org/wiki/Don_Quixote"
      new_tab = true
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true

  [[params.links]]
    [[params.links.link]]
      name = "Goodreads"
      href = "https://www.goodreads.com/book/show/3836.Don_Quixote"
      new_tab = true
    [[params.links.link]]
      name = "Gutenberg"
      href = "https://www.gutenberg.org/files/996/996-h/996-h.htm"
      new_tab = true
    [[params.links.link]]
      name = "Twitter"
      href = "https://twitter.com/search?q=%23twijote%20source%3Atwijote&src=typed_query&f=live"
      new_tab = true
    [[params.links.link]]
      name = "Creator"
      href = "https://sidverma.io"
      new_tab = true